name: spacemade
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23939659027382731
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.75
  lightness: 0.736686835763976
  saturation: 0.46761661558412015
  rhythmicContrast: 0.7623609742149711
purpose: []
